# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster.2.kml.py
# Created on: 2014-02-14 08:44:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
boboli_nass_v6_tif = "boboli.nass.v6.tif"
boboli_nass_v6_kmz = "D:\\Chicago_Grasslands\\MAPS\\boboli.nass.v6.kmz"

# Process: Layer To KML
arcpy.LayerToKML_conversion(boboli_nass_v6_tif, boboli_nass_v6_kmz, "1", "true", "DEFAULT", "1024", "96", "CLAMPED_TO_GROUND")

